### ISSUE TITLE
Bugs in Name Auctions page

### ISSUE THREAD

**Issue by davidyuk** [aeternity/mdw-frontend#162]
Reproducible on https://explorer.aeternity.io/auctions

## Shows the same names on futures pages

After pressing load more you will see the same name auctions as on the previous (initial) page.

## Stuck on "Loading..." after switching from "Expiring soon" to "Name" in combobox

With errors in console:
```
8fc5076.js:2 GET https://mainnet.aeternity.io/mdw//names/auctions?by=name&page=1&limit=10 500

8676c96.js:1 Error: While calling get_all_auctions ({by, direction, page, limit}), GET to https://mainnet.aeternity.io/mdw//names/auctions failed with 500: "Internal Server Error"
    at t.exports (8fc5076.js:2:158339)
    at t.exports (8fc5076.js:2:191584)
    at XMLHttpRequest._.onreadystatechange (8fc5076.js:2:157183)
    
8fc5076.js:2 TypeError: Cannot read properties of undefined (reading 'length')
    at f.<anonymous> (9ae04a2.js:1:13017)
    at f.t._render (8fc5076.js:2:36380)
    at f.r (8fc5076.js:2:65816)
    at En.get (8fc5076.js:2:27662)
    at En.run (8fc5076.js:2:28546)
    at Sn (8fc5076.js:2:26645)
    at Array.<anonymous> (8fc5076.js:2:12935)
    at se (8fc5076.js:2:12379)
```

## ESTIMATED EXPIRATION TIME calculated improperly on initial load

Open the auctions page and reload it, you will see dates like "2025-05-20 18:01:00" instead of "2022-03-23 20:45:00". After switching to another page and back, dates may be calculated properly.

**Comment by ifaouibadi** [comment]
@davidyuk I'm gonna close this since it's been fixed in MDW 1.5.0 update
