### ISSUE TITLE
Display token transfers on account page

### ISSUE THREAD

**Issue by AtanasKrondev** [aeternity/mdw-frontend#80]
Display the token transfers in account page in similar way as in the single transaction view

<img width="500" alt="Screenshot 2021-08-26 at 12 01 28" src="https://user-images.githubusercontent.com/47859124/130934333-b3cecc28-a7f8-4a3b-9abd-d9935a8470f3.png">

Add a filter on account page for different types of transactions

Show "incoming" aex9 transfers

**Comment by marc0olo** [comment]
@AtanasKrondev I am getting errors when trying to start the app locally. should it work? can you clean your local setup and verify please?

```
Failed to compile with 3 errors                                                                                                                                                                                                                   friendly-errors 09:25:19


 ERROR  in ./pages/faucet.vue?vue&type=style&index=0&id=140e5cb1&scoped=true&lang=scss&                                                                                                                                                                   friendly-errors 09:25:19

Module Error (from ./node_modules/sass-loader/dist/cjs.js):                                                                                                                                                                                               friendly-errors 09:25:19
Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (88)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
                                                                                                                                                                                                                                                          friendly-errors 09:25:19
 @ ./node_modules/vue-style-loader??ref--7-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./pages/faucet.vue?vue&type=style&index=0&id=140e5cb1&scoped=true&lang=scss& 4:14-392 14:3-18:5 15:22-400
 @ ./pages/faucet.vue?vue&type=style&index=0&id=140e5cb1&scoped=true&lang=scss&
 @ ./pages/faucet.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
                                                                                                                                                                                                                                                          friendly-errors 09:25:19

 ERROR  in ./styles/index.scss                                                                                                                                                                                                                            friendly-errors 09:25:19

Module build failed (from ./node_modules/postcss-loader/src/index.js):                                                                                                                                                                                    friendly-errors 09:25:19
Error: PostCSS received undefined instead of CSS string
    at new Input (/home/marc0olo/git/aeternity/mdw-frontend/node_modules/postcss/lib/input.js:38:13)
    at parse (/home/marc0olo/git/aeternity/mdw-frontend/node_modules/postcss/lib/parse.js:13:15)
    at new LazyResult (/home/marc0olo/git/aeternity/mdw-frontend/node_modules/postcss/lib/lazy-result.js:64:16)
    at Processor.<anonymous> (/home/marc0olo/git/aeternity/mdw-frontend/node_modules/postcss/lib/processor.js:142:12)
    at Processor.process (/home/marc0olo/git/aeternity/mdw-frontend/node_modules/postcss/lib/processor.js:121:23)
    at /home/marc0olo/git/aeternity/mdw-frontend/node_modules/postcss-loader/src/index.js:141:8
                                                                                                                                                                                                                                                          friendly-errors 09:25:19
 @ ./styles/index.scss 4:14-216 14:3-18:5 15:22-224
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
                                                                                                                                                                                                                                                          friendly-errors 09:25:19

 ERROR  in ./pages/faucet.vue?vue&type=style&index=0&id=140e5cb1&scoped=true&lang=scss&                                                                                                                                                                   friendly-errors 09:25:19

Module build failed (from ./node_modules/postcss-loader/src/index.js):                                                                                                                                                                                    friendly-errors 09:25:19
Error: PostCSS received undefined instead of CSS string
    at new Input (/home/marc0olo/git/aeternity/mdw-frontend/node_modules/postcss/lib/input.js:38:13)
    at parse (/home/marc0olo/git/aeternity/mdw-frontend/node_modules/postcss/lib/parse.js:13:15)
    at new LazyResult (/home/marc0olo/git/aeternity/mdw-frontend/node_modules/postcss/lib/lazy-result.js:64:16)
    at Processor.<anonymous> (/home/marc0olo/git/aeternity/mdw-frontend/node_modules/postcss/lib/processor.js:142:12)
    at Processor.process (/home/marc0olo/git/aeternity/mdw-frontend/node_modules/postcss/lib/processor.js:121:23)
    at /home/marc0olo/git/aeternity/mdw-frontend/node_modules/postcss-loader/src/index.js:141:8
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
                                                                                                                                                                                                                                                          friendly-errors 09:25:19
 @ ./node_modules/vue-style-loader??ref--7-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./pages/faucet.vue?vue&type=style&index=0&id=140e5cb1&scoped=true&lang=scss& 4:14-392 14:3-18:5 15:22-400
 @ ./pages/faucet.vue?vue&type=style&index=0&id=140e5cb1&scoped=true&lang=scss&
 @ ./pages/faucet.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
                                                                                                                                                                                                                                                          friendly-errors 09:25:19
ℹ Watching ~/assets/sprite/svg for new icons                                                                                                                                                                                                           @nuxtjs/svg-sprite 09:25:19
ℹ Waiting for file changes                                                                                                                                                                                                                                                09:25:19
ℹ Memory usage: 378 MB (RSS: 593 MB)                                                                                                                                                                                                                                      09:25:19
ℹ Listening on: http://localhost:3000/                                           
```
